baseURL = 'https://navroopsinghsandhu.github.io/myportfolio/'
languageCode = 'en-us'
title = "A Software Developer's CV"
theme = 'm10c'


[params]
  author = "Navroop Singh"
  description = "On a a fun journey of Software Development"
  [[params.social]]
    icon = "github"
    icon_pack = "fab"
    url = "https://github.com/navroopsinghsandhu"
  [[params.social]]
    icon = "linkedin"
    icon_pack = "fab"
    url = "https://www.linkedin.com/in/navroop-singh-b985aa16a/"